## 描述（可选）
#description = ""
## 主页地址（可选）
#url = "https://github.com/xxxxxxxxxxx/xxxxx"
## 起始年份（可选）
#inceptionYear = "2024"
#
## 组织信息（可选）
#[organization]
#name = "xxxxxxxxxxx"
#url = "https://github.com/xxxxxxxxxxx"
#
## 版本控制信息（可选）
#[scm]
#url = "https://github.com/xxxxxxxxxxx/xxxxx"
#connection = "scm:git:git://github.com/xxxxxxxxxxx/xxxxx.git"
#developerConnection = "scm:git:ssh://github.com:xxxxxxxxxxx/xxxxx.git"
#
## 许可证信息（可选）
#[license]
#name = "The Apache License, Version 2.0"
#url = "https://www.apache.org/licenses/LICENSE-2.0.txt"
#
## 项目开发者信息（可选）
##[[developers]]
##name = "xxx"
##email = "xxx@xxx.xxx"
##key = "XXXXXXXXXXXXXXXX"