group = "xxxx.xxxxxxxxxx.xxxxx"

# 版本号组成：major.minor.revision
[version]
# 主版本号（major）：当存在兼容性变化时，主版本号 +1，次版本号和修订号清零
major = 0
# 次版本号（minor）：当添加新功能时，次版本号 +1，修订号清零
minor = 1
# 修订号（revision）：当有漏洞被修复时，修订号 +1
revision = 0
## 标签（tag）（可选）：用于标记版本，如：SNAPSHOT
#tag = "SNAPSHOT"